### ISSUE TITLE
Gradle 7 Support

### ISSUE THREAD

**Issue by Laarryy** [cschabl/activejdbc-gradle-plugin#11]
Hello! I've made sure to check for other issues here before reporting this.

It appears that the `compile` configuration as present in the build.gradle of this project, and not `implementation`, is preventing compatibility with Gradle 7.1.

I believe it is a simple replacement, as Gradle's site documents here: https://docs.gradle.org/current/userguide/upgrading_version_6.html and here: https://i.imgur.com/Q0ucPVs.png however I am not very experienced in writing Gradle plugins at all. If you could take a look I would really appreciate it!

**Comment by cschabl** [comment]
@Laarryy , as a first step I created a [PR](https://github.com/javalite/javalite-examples/pull/28) for upgrading the Gradle version of  javalite's Gradle example

**Comment by cschabl** [comment]
@Laarryy , I've published the version 1.6-beta.1 of the plugin that supports Gradle 7.
Could you try it and give me feedback?

**Comment by cschabl** [comment]
Fixed in version 2.0.

**Comment by Laarryy** [comment]
Hello! My apologies, I've just received the notification of activity here when you closed the issue. I tested it locally and I'm no longer getting the error, thank you for the rapid and functional update!
