### ISSUE TITLE
UnsupportedClassVersionError with version 2.0.2

### ISSUE THREAD

**Issue by arjopoldervaart** [cschabl/activejdbc-gradle-plugin#13]
Hi, 

we get the following issue when running our gradle builds:
java.lang.UnsupportedClassVersionError: de/schablinski/gradle/activejdbc/ActiveJDBCGradlePlugin has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

We run our gradle builds with the settings (backwards compatibility for legacy platforms):
sourceCompatibility = 1.8
targetCompatibility = 1.8

and since version 2.0.2 our gradle builds do not run anymore. We switched back to version 2.0.1 for now, but is there something else we can do to use the latest version?

Kind regards, 
Arjo Poldervaart

**Comment by cschabl** [comment]
Hi Arjo,
release 2.0.2 has been built with JDK 17, unfortunately.
But you can stay with version 2.0.1 for now, because 2.0.2 only contains a fix for a Java-17 compatability issue.

I will fix this issue the next days.

**Comment by arjopoldervaart** [comment]
Hi Christof, thanks for the quick response 👍

**Comment by cschabl** [comment]
Fixed in version 2.0.3

**Comment by arjopoldervaart** [comment]
thanks, I see our builds running again, but strangely also with version 2.0.2?

**Comment by cschabl** [comment]
Hi Arjo,
I still get this error when I run activejdbc-gradle-plugin 2.0.2 in example project with Java 8:
de/schablinski/gradle/activejdbc/ActiveJDBCGradlePlugin has been compiled by a more recent version of the Java Runtime
