### ISSUE TITLE
Check if the new update is needed for JavaLite 3.0

### ISSUE THREAD

**Issue by ipolevoy** [cschabl/activejdbc-gradle-plugin#14]
The new version of JavaLite 30 for Java 16 is being released. It has been already published to the Sonatype repos, and will appear there soon. 

@cschabl see if the plugin  needs an update - this is an FYI. The release is still in progress, with release notes to  follow.

**Comment by cschabl** [comment]
Hi @ipolevoy , I've updated the activejdbc-dependency in the Gradle example of javalite:examples.
See pull request https://github.com/javalite/javalite-examples/pull/52

**Comment by cschabl** [comment]
Added a unit test with activejdbc-3.4-j11
