### ISSUE TITLE
Aggregate all examples under the same root module

### ISSUE THREAD

**Issue by ipolevoy** [cschabl/activejdbc-gradle-plugin#9]
It will be so much easier to upgrade them to a new release!

Also, create a a new page on the site and list all examples.

**Comment by cschabl** [comment]
@ipolevoy , what do you mean exactly? To merge the projects [active-jdbc-gradle-kotlin-example](https://github.com/cschabl/active-jdbc-gradle-kotlin-example), [active-jdbc-gradle-groovy-example](https://github.com/cschabl/active-jdbc-gradle-groovy-example) and Co. into a single one? What about your example project?

**Comment by ipolevoy** [comment]
oops, sorry - I got lost. This was meant for the JavaLite repository, not yours. Stay safe!
